### ISSUE TITLE
Android code?

### ISSUE THREAD

**Issue by samuk** [Rupakpoddar/Bluetooth-operated-car#1]
Hi do you have the code available for the Android app too? Or is that closed source?

Thanks

**Comment by Rupakpoddar** [comment]
Hi @samuk. I created the app using MIT app inventor and hence I do not have any source code to share. Thank you.

**Comment by samuk** [comment]
Would you be up for sharing the link to your appinventor project? Eg http://ai2.appinventor.mit.edu/#5447043509518336
